name: Test

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  coverage:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 5
    - uses: actions/setup-node@v3
      with:
        node-version: '14.20.0'
    - name: Install and run tests
      run: |
        npm ci
        npm run lint
        npm test
        bash <(curl -s https://codecov.io/bash)
        npm run build
